Mamao/fea/create digit box
podcodar/voting-system pull request #21
Opened 2022-07-22 17:55 UTC by Guilherme-BS

# Description

create digitBox component

## Changes
 ### Visual changes 
![Captura de tela de 2022-07-22 14-53-25](https://user-images.githubusercontent.com/73261443/180496407-abcb4893-6954-46c0-9e38-e53b6001eb48.png)

## Board issue

(include here the board issue number to which this PR refers to)

- Closes #12

2022-07-22 18:15 UTC, Joel-leal commented on packages/components/DigitBox.tsx
> +      display="flex"
Acredito que o componente Flex não precisa da propriedade `display="flex"`. Se o componente Flex aqui tem a função apenas de centralizar os dados no centro, podemos usar o componente `Center`. :)

2022-07-22 18:26 UTC, Joel-leal approved these changes

2022-07-22 19:23 UTC, vzsoares requested changes
esta tendo diferença de largura entre dois componentes que estao juntos , isso esta fazendo com que eles fiquem desalinhados dependendo do tamanho da tela
![image](https://user-images.githubusercontent.com/86134825/180512097-57d86162-d4c0-4e4a-8cea-9ba367936def.png)
recomendo que os dois componentes tenham o mesmo tamanho sempre . provavelmente usando porcentagem deve resolver!

2022-07-22 19:23 UTC, vzsoares commented on packages/components/DigitBox.tsx
> +        <Input width="50px" height="70px" border="1px solid black"></Input>
se nao me engano o input é self closing
```suggestion
        <Input width="50px" height="70px" border="1px solid black" />
```

2022-07-22 19:23 UTC, vzsoares commented on packages/components/DigitBox.tsx
> +      w="27vw"
que tal se usarmos porcentagem aq? esse valor de vw esta dando overflow
![image](https://user-images.githubusercontent.com/86134825/180511420-79ffbbba-5477-4ea5-b0cb-46afed68ec91.png)

2022-07-22 19:28 UTC, vzsoares commented on packages/components/DigitBox.tsx
> +        <Spacer width="2rem" />
e se usar gap no flex que envolve esses inputs

2022-07-22 19:29 UTC, vzsoares commented on packages/components/DigitBox.tsx
> +      <Flex padding="3rem">
e se ao inves de padding , usar gap no flex acima ou tambem justfy items : space between

2022-07-22 20:36 UTC, frattezi commented on packages/components/DigitBox.tsx
> +        <Input width="50px" height="70px" border="1px solid black"></Input>
Os inputs tem de ser bloquados, e não permitir que o usuário de um valor a eles, passaremos o `value` diretamente. No momento resolva apenas:
"O usuário não deve ser capaz de inserir valores no input"

2022-07-26 01:13 UTC, vzsoares approved these changes
show !! só um detalhe , no <Input . pra ficar show acho q é só colocar a propriedade de  `cursor` para default. [ex](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor)

2022-07-26 16:00 UTC, frattezi approved these changes
Muito bom mamão ! 🚀

2022-07-26 22:03 UTC, merged